[2025-02-07T13:46:28.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T13:46:28.044+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T13:46:23.223832+00:00 [queued]>
[2025-02-07T13:46:28.049+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T13:46:23.223832+00:00 [queued]>
[2025-02-07T13:46:28.049+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T13:46:28.058+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): pre_deployment_checks> on 2025-02-07 13:46:23.223832+00:00
[2025-02-07T13:46:28.065+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=94) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T13:46:28.067+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-02-07T13:46:28.068+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'pre_deployment_checks', 'manual__2025-02-07T13:46:23.223832+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmp5tw6obuk']
[2025-02-07T13:46:28.069+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask pre_deployment_checks
[2025-02-07T13:46:28.127+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T13:46:23.223832+00:00 [running]> on host bb7da6492d98
[2025-02-07T13:46:28.192+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='pre_deployment_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T13:46:23.223832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T13:46:23.223832+00:00'
[2025-02-07T13:46:28.194+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T13:46:28.194+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T13:46:28.195+0000] {logging_mixin.py:190} INFO - Current task name:pre_deployment_checks state:running start_date:2025-02-07 13:46:28.045032+00:00
[2025-02-07T13:46:28.196+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-07T13:46:28.196+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T13:46:28.199+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-07T13:46:28.208+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv_b95s88l --system-site-packages --python=python
[2025-02-07T13:46:28.215+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T13:46:29.409+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 437ms
[2025-02-07T13:46:29.411+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv_b95s88l, clear=False, no_vcs_ignore=False, global=True)
[2025-02-07T13:46:29.412+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-07T13:46:29.413+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-07T13:46:29.414+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-07T13:46:29.432+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv_b95s88l/bin/pip install -r /tmp/venv_b95s88l/requirements.txt
[2025-02-07T13:46:29.434+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T13:46:30.506+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv_b95s88l/requirements.txt (line 1)) (2.1.4)
[2025-02-07T13:46:30.510+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv_b95s88l/requirements.txt (line 1)) (1.26.4)
[2025-02-07T13:46:30.511+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv_b95s88l/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-07T13:46:30.511+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv_b95s88l/requirements.txt (line 1)) (2024.2)
[2025-02-07T13:46:30.512+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv_b95s88l/requirements.txt (line 1)) (2024.2)
[2025-02-07T13:46:30.514+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venv_b95s88l/requirements.txt (line 1)) (1.17.0)
[2025-02-07T13:46:30.925+0000] {process_utils.py:194} INFO - 
[2025-02-07T13:46:30.925+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-07T13:46:30.926+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-07T13:46:31.001+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv_b95s88l/bin/python /tmp/venv-calllfstjsre/script.py /tmp/venv-calllfstjsre/script.in /tmp/venv-calllfstjsre/script.out /tmp/venv-calllfstjsre/string_args.txt /tmp/venv-calllfstjsre/termination.log
[2025-02-07T13:46:31.002+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T13:46:33.447+0000] {process_utils.py:194} INFO - [2025-02-07T13:46:33.445+0000] {script.py:23} INFO - Starting pre-deployment checks...
[2025-02-07T13:46:33.451+0000] {process_utils.py:194} INFO - [2025-02-07T13:46:33.450+0000] {script.py:38} INFO - Pre-deployment checks completed
[2025-02-07T13:46:33.803+0000] {python.py:240} INFO - Done. Returned value was: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-07T13:46:33.450869'}
[2025-02-07T13:46:33.842+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T13:46:33.843+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=pre_deployment_checks, run_id=manual__2025-02-07T13:46:23.223832+00:00, execution_date=20250207T134623, start_date=20250207T134628, end_date=20250207T134633
[2025-02-07T13:46:33.854+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T13:46:33.854+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T13:46:33.855+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-07 13:46:23.239307+00:00
[2025-02-07T13:46:33.855+0000] {logging_mixin.py:190} INFO - Task hostname:bb7da6492d98 operator:PythonVirtualenvOperator
[2025-02-07T13:46:33.905+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T13:46:33.926+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T13:46:33.928+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
