[2025-02-07T14:54:01.119+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T14:54:01.127+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_versioned.download_stack manual__2025-02-07T14:53:52.605876+00:00 [queued]>
[2025-02-07T14:54:01.131+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_versioned.download_stack manual__2025-02-07T14:53:52.605876+00:00 [queued]>
[2025-02-07T14:54:01.131+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T14:54:01.138+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): download_stack> on 2025-02-07 14:53:52.605876+00:00
[2025-02-07T14:54:01.142+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=631) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T14:54:01.143+0000] {standard_task_runner.py:72} INFO - Started process 632 to run task
[2025-02-07T14:54:01.144+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_versioned', 'download_stack', 'manual__2025-02-07T14:53:52.605876+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_versioned.py', '--cfg-path', '/tmp/tmpr3ddkie4']
[2025-02-07T14:54:01.145+0000] {standard_task_runner.py:105} INFO - Job 238: Subtask download_stack
[2025-02-07T14:54:01.179+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_versioned.download_stack manual__2025-02-07T14:53:52.605876+00:00 [running]> on host 35f5723d0861
[2025-02-07T14:54:01.225+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_versioned' AIRFLOW_CTX_TASK_ID='download_stack' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T14:53:52.605876+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T14:53:52.605876+00:00'
[2025-02-07T14:54:01.226+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T14:54:01.227+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T14:54:01.227+0000] {logging_mixin.py:190} INFO - Current task name:download_stack state:running start_date:2025-02-07 14:54:01.127574+00:00
[2025-02-07T14:54:01.227+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned and current dag run status:running
[2025-02-07T14:54:01.228+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T14:54:01.228+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-07T14:54:01.229+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvjak0ezqo --system-site-packages --python=python
[2025-02-07T14:54:01.229+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:54:01.722+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 144ms
[2025-02-07T14:54:01.723+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvjak0ezqo, clear=False, no_vcs_ignore=False, global=True)
[2025-02-07T14:54:01.723+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-07T14:54:01.723+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-07T14:54:01.724+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-07T14:54:01.747+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvjak0ezqo/bin/pip install -r /tmp/venvjak0ezqo/requirements.txt
[2025-02-07T14:54:01.749+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:54:02.788+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvjak0ezqo/requirements.txt (line 1)) (2.1.4)
[2025-02-07T14:54:02.793+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvjak0ezqo/requirements.txt (line 1)) (1.26.4)
[2025-02-07T14:54:02.794+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvjak0ezqo/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-07T14:54:02.795+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvjak0ezqo/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:54:02.795+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvjak0ezqo/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:54:02.798+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvjak0ezqo/requirements.txt (line 1)) (1.17.0)
[2025-02-07T14:54:03.194+0000] {process_utils.py:194} INFO - 
[2025-02-07T14:54:03.194+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-07T14:54:03.195+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-07T14:54:03.260+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvjak0ezqo/bin/python /tmp/venv-callhh1znuz1/script.py /tmp/venv-callhh1znuz1/script.in /tmp/venv-callhh1znuz1/script.out /tmp/venv-callhh1znuz1/string_args.txt /tmp/venv-callhh1znuz1/termination.log
[2025-02-07T14:54:03.261+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:54:05.093+0000] {process_utils.py:194} INFO - [2025-02-07T14:54:05.092+0000] {script.py:24} INFO - Starting download stack...
[2025-02-07T14:54:15.103+0000] {process_utils.py:194} INFO - [2025-02-07T14:54:15.101+0000] {script.py:40} INFO - Download stack completed:
[2025-02-07T14:54:15.105+0000] {process_utils.py:194} INFO - Total size: 1200.0MB
[2025-02-07T14:54:15.105+0000] {process_utils.py:194} INFO - Total time: 240s
[2025-02-07T14:54:15.106+0000] {process_utils.py:194} INFO - Download speed: 5.0MB/s
[2025-02-07T14:54:15.530+0000] {python.py:240} INFO - Done. Returned value was: {'stacks': ['baseos', 'gi'], 'total_size_mb': 1200.0, 'total_time_seconds': 240, 'download_speed_mbs': 5.0, 'status': 'success', 'details': [{'stack': 'baseos', 'size_mb': 1000, 'status': 'completed', 'time': 180}, {'stack': 'gi', 'size_mb': 200, 'status': 'completed', 'time': 60}], 'timestamp': '2025-02-07T14:54:15.101404'}
[2025-02-07T14:54:15.573+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T14:54:15.574+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_versioned, task_id=download_stack, run_id=manual__2025-02-07T14:53:52.605876+00:00, execution_date=20250207T145352, start_date=20250207T145401, end_date=20250207T145415
[2025-02-07T14:54:15.584+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T14:54:15.585+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T14:54:15.585+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned queued_at:2025-02-07 14:53:52.621140+00:00
[2025-02-07T14:54:15.585+0000] {logging_mixin.py:190} INFO - Task hostname:35f5723d0861 operator:PythonVirtualenvOperator
[2025-02-07T14:54:15.608+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T14:54:15.651+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T14:54:15.653+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
