[2025-02-10T09:20:35.011+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T09:20:35.022+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.download_stack manual__2025-02-10T09:20:23.318304+00:00 [queued]>
[2025-02-10T09:20:35.028+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.download_stack manual__2025-02-10T09:20:23.318304+00:00 [queued]>
[2025-02-10T09:20:35.029+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T09:20:35.036+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): download_stack> on 2025-02-10 09:20:23.318304+00:00
[2025-02-10T09:20:35.045+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14324) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T09:20:35.046+0000] {standard_task_runner.py:72} INFO - Started process 14325 to run task
[2025-02-10T09:20:35.047+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'download_stack', 'manual__2025-02-10T09:20:23.318304+00:00', '--job-id', '505', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmptsjhmvwj']
[2025-02-10T09:20:35.048+0000] {standard_task_runner.py:105} INFO - Job 505: Subtask download_stack
[2025-02-10T09:20:35.090+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.download_stack manual__2025-02-10T09:20:23.318304+00:00 [running]> on host 1999c8c59930
[2025-02-10T09:20:35.141+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='download_stack' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:20:23.318304+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:20:23.318304+00:00'
[2025-02-10T09:20:35.142+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T09:20:35.143+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T09:20:35.143+0000] {logging_mixin.py:190} INFO - Current task name:download_stack state:running start_date:2025-02-10 09:20:35.022564+00:00
[2025-02-10T09:20:35.143+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-10T09:20:35.143+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T09:20:35.144+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T09:20:35.145+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvr2q7810q --system-site-packages --python=python
[2025-02-10T09:20:35.146+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:20:35.876+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 288ms
[2025-02-10T09:20:35.884+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvr2q7810q, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T09:20:35.885+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T09:20:35.893+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T09:20:35.894+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T09:20:35.902+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvr2q7810q/bin/pip install -r /tmp/venvr2q7810q/requirements.txt
[2025-02-10T09:20:35.903+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:20:37.004+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvr2q7810q/requirements.txt (line 1)) (2.1.4)
[2025-02-10T09:20:37.009+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvr2q7810q/requirements.txt (line 1)) (1.26.4)
[2025-02-10T09:20:37.009+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvr2q7810q/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T09:20:37.010+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvr2q7810q/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:20:37.011+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvr2q7810q/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:20:37.012+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvr2q7810q/requirements.txt (line 1)) (1.17.0)
[2025-02-10T09:20:37.414+0000] {process_utils.py:194} INFO - 
[2025-02-10T09:20:37.415+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T09:20:37.415+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T09:20:37.476+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvr2q7810q/bin/python /tmp/venv-callb2_azh4h/script.py /tmp/venv-callb2_azh4h/script.in /tmp/venv-callb2_azh4h/script.out /tmp/venv-callb2_azh4h/string_args.txt /tmp/venv-callb2_azh4h/termination.log
[2025-02-10T09:20:37.477+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:20:39.614+0000] {process_utils.py:194} INFO - [2025-02-10T09:20:39.610+0000] {script.py:30} INFO - Starting download stack...
[2025-02-10T09:20:49.623+0000] {process_utils.py:194} INFO - [2025-02-10T09:20:49.621+0000] {script.py:46} INFO - Writing download report to to: /opt/***/data/download_report_from_v1.0.0.json
[2025-02-10T09:20:49.627+0000] {process_utils.py:194} INFO - [2025-02-10T09:20:49.625+0000] {script.py:50} INFO - Download stack completed:
[2025-02-10T09:20:49.628+0000] {process_utils.py:194} INFO - Total size: 1200.0MB
[2025-02-10T09:20:49.628+0000] {process_utils.py:194} INFO - Total time: 240s
[2025-02-10T09:20:49.628+0000] {process_utils.py:194} INFO - Download speed: 5.0MB/s
[2025-02-10T09:20:50.085+0000] {python.py:240} INFO - Done. Returned value was: {'stacks': ['baseos', 'gi'], 'total_size_mb': 1200.0, 'total_time_seconds': 240, 'download_speed_mbs': 5.0, 'status': 'success', 'details': [{'stack': 'baseos', 'size_mb': 1000, 'status': 'completed', 'time': 180}, {'stack': 'gi', 'size_mb': 200, 'status': 'completed', 'time': 60}], 'timestamp': '2025-02-10T09:20:49.621091'}
[2025-02-10T09:20:50.118+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T09:20:50.119+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=download_stack, run_id=manual__2025-02-10T09:20:23.318304+00:00, execution_date=20250210T092023, start_date=20250210T092035, end_date=20250210T092050
[2025-02-10T09:20:50.127+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T09:20:50.128+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T09:20:50.128+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-10 09:20:23.365531+00:00
[2025-02-10T09:20:50.128+0000] {logging_mixin.py:190} INFO - Task hostname:1999c8c59930 operator:PythonVirtualenvOperator
[2025-02-10T09:20:50.172+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T09:20:50.198+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T09:20:50.200+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
