[2025-02-10T09:39:18.743+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T09:39:18.754+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.download_stack manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:39:18.760+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.download_stack manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:39:18.760+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T09:39:18.768+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): download_stack> on 2025-02-10 09:39:08.243353+00:00
[2025-02-10T09:39:18.774+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14899) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T09:39:18.776+0000] {standard_task_runner.py:72} INFO - Started process 14900 to run task
[2025-02-10T09:39:18.776+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'download_stack', 'manual__2025-02-10T09:39:08.243353+00:00', '--job-id', '574', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpfqxfcwlm']
[2025-02-10T09:39:18.778+0000] {standard_task_runner.py:105} INFO - Job 574: Subtask download_stack
[2025-02-10T09:39:18.824+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.download_stack manual__2025-02-10T09:39:08.243353+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T09:39:18.887+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='download_stack' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:39:08.243353+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:39:08.243353+00:00'
[2025-02-10T09:39:18.888+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T09:39:18.889+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T09:39:18.889+0000] {logging_mixin.py:190} INFO - Current task name:download_stack state:running start_date:2025-02-10 09:39:18.754938+00:00
[2025-02-10T09:39:18.889+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T09:39:18.889+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T09:39:18.890+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T09:39:18.891+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvq2tu1mvf --system-site-packages --python=python
[2025-02-10T09:39:18.893+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:39:19.709+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 201ms
[2025-02-10T09:39:19.710+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvq2tu1mvf, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T09:39:19.711+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T09:39:19.712+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T09:39:19.713+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T09:39:19.742+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvq2tu1mvf/bin/pip install -r /tmp/venvq2tu1mvf/requirements.txt
[2025-02-10T09:39:19.743+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:39:20.875+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvq2tu1mvf/requirements.txt (line 1)) (2.1.4)
[2025-02-10T09:39:20.894+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvq2tu1mvf/requirements.txt (line 1)) (1.26.4)
[2025-02-10T09:39:20.895+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvq2tu1mvf/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T09:39:20.896+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvq2tu1mvf/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:39:20.897+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvq2tu1mvf/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:39:20.898+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvq2tu1mvf/requirements.txt (line 1)) (1.17.0)
[2025-02-10T09:39:21.353+0000] {process_utils.py:194} INFO - 
[2025-02-10T09:39:21.354+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T09:39:21.355+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T09:39:21.431+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvq2tu1mvf/bin/python /tmp/venv-call4zo6umfi/script.py /tmp/venv-call4zo6umfi/script.in /tmp/venv-call4zo6umfi/script.out /tmp/venv-call4zo6umfi/string_args.txt /tmp/venv-call4zo6umfi/termination.log
[2025-02-10T09:39:21.432+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:39:23.810+0000] {process_utils.py:194} INFO - [2025-02-10T09:39:23.809+0000] {script.py:30} INFO - Starting download stack...
[2025-02-10T09:39:33.826+0000] {process_utils.py:194} INFO - [2025-02-10T09:39:33.823+0000] {script.py:46} INFO - Writing download report to to: /opt/***/data/download_report_from_v1.0.0.json
[2025-02-10T09:39:33.829+0000] {process_utils.py:194} INFO - [2025-02-10T09:39:33.829+0000] {script.py:50} INFO - Download stack completed:
[2025-02-10T09:39:33.830+0000] {process_utils.py:194} INFO - Total size: 1200.0MB
[2025-02-10T09:39:33.831+0000] {process_utils.py:194} INFO - Total time: 240s
[2025-02-10T09:39:33.831+0000] {process_utils.py:194} INFO - Download speed: 5.0MB/s
[2025-02-10T09:39:34.409+0000] {python.py:240} INFO - Done. Returned value was: {'stacks': ['baseos', 'gi'], 'total_size_mb': 1200.0, 'total_time_seconds': 240, 'download_speed_mbs': 5.0, 'status': 'success', 'details': [{'stack': 'baseos', 'size_mb': 1000, 'status': 'completed', 'time': 180}, {'stack': 'gi', 'size_mb': 200, 'status': 'completed', 'time': 60}], 'timestamp': '2025-02-10T09:39:33.823472'}
[2025-02-10T09:39:34.454+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T09:39:34.457+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_rollback, task_id=download_stack, run_id=manual__2025-02-10T09:39:08.243353+00:00, execution_date=20250210T093908, start_date=20250210T093918, end_date=20250210T093934
[2025-02-10T09:39:34.471+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T09:39:34.472+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T09:39:34.472+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback queued_at:2025-02-10 09:39:08.258989+00:00
[2025-02-10T09:39:34.472+0000] {logging_mixin.py:190} INFO - Task hostname:fbc98e9fe6bb operator:PythonVirtualenvOperator
[2025-02-10T09:39:34.494+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T09:39:34.525+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T09:39:34.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
