[2025-02-10T12:48:00.924+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:48:00.935+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.run_pre_check manual__2025-02-10T12:47:31.086830+00:00 [queued]>
[2025-02-10T12:48:00.940+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.run_pre_check manual__2025-02-10T12:47:31.086830+00:00 [queued]>
[2025-02-10T12:48:00.940+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:48:00.949+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): run_pre_check> on 2025-02-10 12:47:31.086830+00:00
[2025-02-10T12:48:00.967+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=562) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:48:00.970+0000] {standard_task_runner.py:72} INFO - Started process 565 to run task
[2025-02-10T12:48:00.970+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'run_pre_check', 'manual__2025-02-10T12:47:31.086830+00:00', '--job-id', '619', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmpc77qeb1k']
[2025-02-10T12:48:00.972+0000] {standard_task_runner.py:105} INFO - Job 619: Subtask run_pre_check
[2025-02-10T12:48:01.007+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.run_pre_check manual__2025-02-10T12:47:31.086830+00:00 [running]> on host 1999c8c59930
[2025-02-10T12:48:01.058+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='run_pre_check' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:47:31.086830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:47:31.086830+00:00'
[2025-02-10T12:48:01.059+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:48:01.060+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:48:01.060+0000] {logging_mixin.py:190} INFO - Current task name:run_pre_check state:running start_date:2025-02-10 12:48:00.935441+00:00
[2025-02-10T12:48:01.060+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-10T12:48:01.060+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:48:01.061+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T12:48:01.062+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvz6s77jzv --system-site-packages --python=python
[2025-02-10T12:48:01.063+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:48:01.737+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 233ms
[2025-02-10T12:48:01.739+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvz6s77jzv, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T12:48:01.739+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T12:48:01.740+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T12:48:01.740+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T12:48:01.760+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvz6s77jzv/bin/pip install -r /tmp/venvz6s77jzv/requirements.txt
[2025-02-10T12:48:01.762+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:48:02.895+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvz6s77jzv/requirements.txt (line 1)) (2.1.4)
[2025-02-10T12:48:02.902+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvz6s77jzv/requirements.txt (line 1)) (1.26.4)
[2025-02-10T12:48:02.903+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvz6s77jzv/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T12:48:02.905+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvz6s77jzv/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:48:02.906+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvz6s77jzv/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:48:02.908+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvz6s77jzv/requirements.txt (line 1)) (1.17.0)
[2025-02-10T12:48:03.278+0000] {process_utils.py:194} INFO - 
[2025-02-10T12:48:03.278+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T12:48:03.279+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T12:48:03.350+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-02-10T12:48:03.359+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvz6s77jzv/bin/python /tmp/venv-callvn7uifxz/script.py /tmp/venv-callvn7uifxz/script.in /tmp/venv-callvn7uifxz/script.out /tmp/venv-callvn7uifxz/string_args.txt /tmp/venv-callvn7uifxz/termination.log
[2025-02-10T12:48:03.361+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:48:05.415+0000] {process_utils.py:194} INFO - [2025-02-10T12:48:05.414+0000] {script.py:23} INFO - Starting run pre-checks...
[2025-02-10T12:48:05.418+0000] {process_utils.py:194} INFO - [2025-02-10T12:48:05.415+0000] {script.py:26} INFO - Pre Deployment Report: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-10T12:47:40.751967'}
[2025-02-10T12:48:05.418+0000] {process_utils.py:194} INFO - [2025-02-10T12:48:05.417+0000] {script.py:41} INFO - Pre-checks completed:
[2025-02-10T12:48:05.419+0000] {process_utils.py:194} INFO - Total memory usage: 1536%
[2025-02-10T12:48:05.419+0000] {process_utils.py:194} INFO - Status: PASS
[2025-02-10T12:48:05.920+0000] {python.py:240} INFO - Done. Returned value was: {'total_memory_usage_mb': 1536, 'checks_passed': True, 'timestamp': '2025-02-10T12:48:05.417426'}
[2025-02-10T12:48:05.980+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:48:05.981+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=run_pre_check, run_id=manual__2025-02-10T12:47:31.086830+00:00, execution_date=20250210T124731, start_date=20250210T124800, end_date=20250210T124805
[2025-02-10T12:48:05.998+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T12:48:05.998+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T12:48:05.999+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-10 12:47:31.122350+00:00
[2025-02-10T12:48:05.999+0000] {logging_mixin.py:190} INFO - Task hostname:1999c8c59930 operator:PythonVirtualenvOperator
[2025-02-10T12:48:06.057+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T12:48:06.088+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T12:48:06.089+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
