[2025-02-05T13:34:41.430+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T13:34:41.440+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: external_signal_workflow.task_1 manual__2025-02-05T13:34:39.144956+00:00 [queued]>
[2025-02-05T13:34:41.445+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: external_signal_workflow.task_1 manual__2025-02-05T13:34:39.144956+00:00 [queued]>
[2025-02-05T13:34:41.445+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-05T13:34:41.454+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): task_1> on 2025-02-05 13:34:39.144956+00:00
[2025-02-05T13:34:41.461+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T13:34:41.463+0000] {standard_task_runner.py:72} INFO - Started process 1225 to run task
[2025-02-05T13:34:41.463+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'external_signal_workflow', 'task_1', 'manual__2025-02-05T13:34:39.144956+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/external_signal_workflow.py', '--cfg-path', '/tmp/tmpd_5i3vpn']
[2025-02-05T13:34:41.464+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask task_1
[2025-02-05T13:34:41.787+0000] {task_command.py:467} INFO - Running <TaskInstance: external_signal_workflow.task_1 manual__2025-02-05T13:34:39.144956+00:00 [running]> on host ***-worker-2
[2025-02-05T13:34:41.829+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='external_signal_workflow' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T13:34:39.144956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T13:34:39.144956+00:00'
[2025-02-05T13:34:41.830+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-05T13:34:41.830+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-05T13:34:41.830+0000] {logging_mixin.py:190} INFO - Current task name:task_1 state:running start_date:2025-02-05 13:34:41.440848+00:00
[2025-02-05T13:34:41.831+0000] {logging_mixin.py:190} INFO - Dag name:external_signal_workflow and current dag run status:running
[2025-02-05T13:34:41.831+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T13:34:41.831+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-05T13:34:41.832+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvx1_kj5rw --python=python
[2025-02-05T13:34:41.835+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T13:34:42.666+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 321ms
[2025-02-05T13:34:42.667+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvx1_kj5rw, clear=False, no_vcs_ignore=False, global=False)
[2025-02-05T13:34:42.667+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-05T13:34:42.667+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-05T13:34:42.667+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-05T13:34:42.687+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvx1_kj5rw/bin/pip install -r /tmp/venvx1_kj5rw/requirements.txt
[2025-02-05T13:34:42.688+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T13:34:43.746+0000] {process_utils.py:194} INFO - Collecting pandas==2.1.4 (from -r /tmp/venvx1_kj5rw/requirements.txt (line 1))
[2025-02-05T13:34:43.872+0000] {process_utils.py:194} INFO -   Downloading pandas-2.1.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (18 kB)
[2025-02-05T13:34:44.037+0000] {process_utils.py:194} INFO - Collecting numpy<2,>=1.26.0 (from pandas==2.1.4->-r /tmp/venvx1_kj5rw/requirements.txt (line 1))
[2025-02-05T13:34:44.064+0000] {process_utils.py:194} INFO -   Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (62 kB)
[2025-02-05T13:34:44.137+0000] {process_utils.py:194} INFO - Collecting python-dateutil>=2.8.2 (from pandas==2.1.4->-r /tmp/venvx1_kj5rw/requirements.txt (line 1))
[2025-02-05T13:34:44.163+0000] {process_utils.py:194} INFO -   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2025-02-05T13:34:44.247+0000] {process_utils.py:194} INFO - Collecting pytz>=2020.1 (from pandas==2.1.4->-r /tmp/venvx1_kj5rw/requirements.txt (line 1))
[2025-02-05T13:34:44.274+0000] {process_utils.py:194} INFO -   Downloading pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
[2025-02-05T13:34:44.313+0000] {process_utils.py:194} INFO - Collecting tzdata>=2022.1 (from pandas==2.1.4->-r /tmp/venvx1_kj5rw/requirements.txt (line 1))
[2025-02-05T13:34:44.348+0000] {process_utils.py:194} INFO -   Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2025-02-05T13:34:44.388+0000] {process_utils.py:194} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvx1_kj5rw/requirements.txt (line 1))
[2025-02-05T13:34:44.413+0000] {process_utils.py:194} INFO -   Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
[2025-02-05T13:34:44.445+0000] {process_utils.py:194} INFO - Downloading pandas-2.1.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.3 MB)
[2025-02-05T13:34:44.821+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 42.4 MB/s eta 0:00:00
[2025-02-05T13:34:44.850+0000] {process_utils.py:194} INFO - Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.9 MB)
[2025-02-05T13:34:45.150+0000] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 46.3 MB/s eta 0:00:00
[2025-02-05T13:34:45.179+0000] {process_utils.py:194} INFO - Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2025-02-05T13:34:45.209+0000] {process_utils.py:194} INFO - Downloading pytz-2025.1-py2.py3-none-any.whl (507 kB)
[2025-02-05T13:34:45.243+0000] {process_utils.py:194} INFO - Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
[2025-02-05T13:34:45.277+0000] {process_utils.py:194} INFO - Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
[2025-02-05T13:34:45.341+0000] {process_utils.py:194} INFO - Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
[2025-02-05T13:34:50.185+0000] {process_utils.py:194} INFO - Successfully installed numpy-1.26.4 pandas-2.1.4 python-dateutil-2.9.0.post0 pytz-2025.1 six-1.17.0 tzdata-2025.1
[2025-02-05T13:34:50.368+0000] {process_utils.py:194} INFO - 
[2025-02-05T13:34:50.368+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-05T13:34:50.369+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-05T13:34:50.462+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.462+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.463+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.463+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:34:50.465+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-02-05T13:34:50.466+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.466+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.467+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.467+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.467+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.468+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.468+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.468+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:34:50.478+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvx1_kj5rw/bin/python /tmp/venv-calllgs7i0za/script.py /tmp/venv-calllgs7i0za/script.in /tmp/venv-calllgs7i0za/script.out /tmp/venv-calllgs7i0za/string_args.txt /tmp/venv-calllgs7i0za/termination.log
[2025-02-05T13:34:50.479+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T13:34:51.043+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2025-02-05T13:34:51.044+0000] {process_utils.py:194} INFO -   File "/tmp/venv-calllgs7i0za/script.py", line 66, in <module>
[2025-02-05T13:34:51.045+0000] {process_utils.py:194} INFO -     res = task_1(*arg_dict["args"], **arg_dict["kwargs"])
[2025-02-05T13:34:51.045+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-05T13:34:51.046+0000] {process_utils.py:194} INFO -   File "/tmp/venv-calllgs7i0za/script.py", line 22, in task_1
[2025-02-05T13:34:51.046+0000] {process_utils.py:194} INFO -     ti = kwargs['ti']  # Task instance for XCom access
[2025-02-05T13:34:51.047+0000] {process_utils.py:194} INFO -          ~~~~~~^^^^^^
[2025-02-05T13:34:51.047+0000] {process_utils.py:194} INFO - KeyError: 'ti'
[2025-02-05T13:34:51.208+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
'ti'
[2025-02-05T13:34:51.217+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-05T13:34:51.217+0000] {logging_mixin.py:190} INFO - Task start:2025-02-05 13:34:41.440848+00:00 end:2025-02-05 13:34:51.216520+00:00 duration:9.775672
[2025-02-05T13:34:51.221+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonVirtualenvOperator): task_1> dag:<DAG: external_signal_workflow> dagrun:<DagRun external_signal_workflow @ 2025-02-05 13:34:39.144956+00:00: manual__2025-02-05T13:34:39.144956+00:00, state:running, queued_at: 2025-02-05 13:34:39.165724+00:00. externally triggered: True>
[2025-02-05T13:34:51.222+0000] {logging_mixin.py:190} INFO - Failure caused by Process returned non-zero exit status 1.
'ti'
[2025-02-05T13:34:51.222+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=external_signal_workflow, task_id=task_1, run_id=manual__2025-02-05T13:34:39.144956+00:00, execution_date=20250205T133439, start_date=20250205T133441, end_date=20250205T133451
[2025-02-05T13:34:51.237+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T13:34:51.238+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task task_1 (Process returned non-zero exit status 1.
'ti'; 1225)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
'ti'
[2025-02-05T13:34:51.271+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-05T13:34:51.293+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T13:34:51.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
