[2025-02-10T09:20:52.268+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T09:20:52.277+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.run_pre_check manual__2025-02-10T09:20:23.318304+00:00 [queued]>
[2025-02-10T09:20:52.281+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.run_pre_check manual__2025-02-10T09:20:23.318304+00:00 [queued]>
[2025-02-10T09:20:52.282+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T09:20:52.289+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): run_pre_check> on 2025-02-10 09:20:23.318304+00:00
[2025-02-10T09:20:52.303+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14290) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T09:20:52.304+0000] {standard_task_runner.py:72} INFO - Started process 14291 to run task
[2025-02-10T09:20:52.305+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'run_pre_check', 'manual__2025-02-10T09:20:23.318304+00:00', '--job-id', '506', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmppc24ywsh']
[2025-02-10T09:20:52.306+0000] {standard_task_runner.py:105} INFO - Job 506: Subtask run_pre_check
[2025-02-10T09:20:52.357+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.run_pre_check manual__2025-02-10T09:20:23.318304+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T09:20:52.414+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='run_pre_check' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:20:23.318304+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:20:23.318304+00:00'
[2025-02-10T09:20:52.415+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T09:20:52.415+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T09:20:52.416+0000] {logging_mixin.py:190} INFO - Current task name:run_pre_check state:running start_date:2025-02-10 09:20:52.278233+00:00
[2025-02-10T09:20:52.416+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-10T09:20:52.416+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T09:20:52.416+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T09:20:52.417+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv7dv71ppv --system-site-packages --python=python
[2025-02-10T09:20:52.418+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:20:53.008+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 203ms
[2025-02-10T09:20:53.009+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv7dv71ppv, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T09:20:53.009+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T09:20:53.010+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T09:20:53.010+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T09:20:53.025+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv7dv71ppv/bin/pip install -r /tmp/venv7dv71ppv/requirements.txt
[2025-02-10T09:20:53.027+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:20:54.042+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv7dv71ppv/requirements.txt (line 1)) (2.1.4)
[2025-02-10T09:20:54.047+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7dv71ppv/requirements.txt (line 1)) (1.26.4)
[2025-02-10T09:20:54.048+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7dv71ppv/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T09:20:54.048+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7dv71ppv/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:20:54.049+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7dv71ppv/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:20:54.051+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venv7dv71ppv/requirements.txt (line 1)) (1.17.0)
[2025-02-10T09:20:54.455+0000] {process_utils.py:194} INFO - 
[2025-02-10T09:20:54.455+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T09:20:54.456+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T09:20:54.525+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-02-10T09:20:54.536+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv7dv71ppv/bin/python /tmp/venv-callgt26g9kv/script.py /tmp/venv-callgt26g9kv/script.in /tmp/venv-callgt26g9kv/script.out /tmp/venv-callgt26g9kv/string_args.txt /tmp/venv-callgt26g9kv/termination.log
[2025-02-10T09:20:54.539+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:20:57.138+0000] {process_utils.py:194} INFO - [2025-02-10T09:20:57.136+0000] {script.py:23} INFO - Starting run pre-checks...
[2025-02-10T09:20:57.149+0000] {process_utils.py:194} INFO - [2025-02-10T09:20:57.137+0000] {script.py:26} INFO - Pre Deployment Report: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-10T09:20:31.906055'}
[2025-02-10T09:20:57.150+0000] {process_utils.py:194} INFO - [2025-02-10T09:20:57.139+0000] {script.py:41} INFO - Pre-checks completed:
[2025-02-10T09:20:57.153+0000] {process_utils.py:194} INFO - Total memory usage: 1536%
[2025-02-10T09:20:57.154+0000] {process_utils.py:194} INFO - Status: PASS
[2025-02-10T09:20:57.563+0000] {python.py:240} INFO - Done. Returned value was: {'total_memory_usage_mb': 1536, 'checks_passed': True, 'timestamp': '2025-02-10T09:20:57.139078'}
[2025-02-10T09:20:57.596+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T09:20:57.597+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=run_pre_check, run_id=manual__2025-02-10T09:20:23.318304+00:00, execution_date=20250210T092023, start_date=20250210T092052, end_date=20250210T092057
[2025-02-10T09:20:57.606+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T09:20:57.606+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T09:20:57.606+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-10 09:20:23.365531+00:00
[2025-02-10T09:20:57.607+0000] {logging_mixin.py:190} INFO - Task hostname:fbc98e9fe6bb operator:PythonVirtualenvOperator
[2025-02-10T09:20:57.661+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T09:20:57.693+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T09:20:57.695+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
