[2025-02-05T14:43:33.198+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T14:43:33.206+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: external_signal_workflow.task_2 manual__2025-02-05T14:43:19.715570+00:00 [queued]>
[2025-02-05T14:43:33.211+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: external_signal_workflow.task_2 manual__2025-02-05T14:43:19.715570+00:00 [queued]>
[2025-02-05T14:43:33.211+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-05T14:43:33.315+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): task_2> on 2025-02-05 14:43:19.715570+00:00
[2025-02-05T14:43:33.322+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2290) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T14:43:33.323+0000] {standard_task_runner.py:72} INFO - Started process 2291 to run task
[2025-02-05T14:43:33.323+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'external_signal_workflow', 'task_2', 'manual__2025-02-05T14:43:19.715570+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/external_signal_workflow.py', '--cfg-path', '/tmp/tmprqqc78jp']
[2025-02-05T14:43:33.324+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask task_2
[2025-02-05T14:43:33.355+0000] {task_command.py:467} INFO - Running <TaskInstance: external_signal_workflow.task_2 manual__2025-02-05T14:43:19.715570+00:00 [running]> on host ***-worker-2
[2025-02-05T14:43:33.407+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='external_signal_workflow' AIRFLOW_CTX_TASK_ID='task_2' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T14:43:19.715570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T14:43:19.715570+00:00'
[2025-02-05T14:43:33.408+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-05T14:43:33.409+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-05T14:43:33.409+0000] {logging_mixin.py:190} INFO - Current task name:task_2 state:running start_date:2025-02-05 14:43:33.207233+00:00
[2025-02-05T14:43:33.409+0000] {logging_mixin.py:190} INFO - Dag name:external_signal_workflow and current dag run status:running
[2025-02-05T14:43:33.409+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T14:43:33.410+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-05T14:43:33.411+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvp2zxfs_4 --python=python
[2025-02-05T14:43:33.411+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T14:43:34.110+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 274ms
[2025-02-05T14:43:34.111+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvp2zxfs_4, clear=False, no_vcs_ignore=False, global=False)
[2025-02-05T14:43:34.112+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-05T14:43:34.112+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-05T14:43:34.113+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-05T14:43:34.133+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvp2zxfs_4/bin/pip install -r /tmp/venvp2zxfs_4/requirements.txt
[2025-02-05T14:43:34.135+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T14:43:35.327+0000] {process_utils.py:194} INFO - Collecting pandas==2.1.4 (from -r /tmp/venvp2zxfs_4/requirements.txt (line 1))
[2025-02-05T14:43:35.336+0000] {process_utils.py:194} INFO -   Using cached pandas-2.1.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (18 kB)
[2025-02-05T14:43:35.503+0000] {process_utils.py:194} INFO - Collecting numpy<2,>=1.26.0 (from pandas==2.1.4->-r /tmp/venvp2zxfs_4/requirements.txt (line 1))
[2025-02-05T14:43:35.506+0000] {process_utils.py:194} INFO -   Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (62 kB)
[2025-02-05T14:43:35.550+0000] {process_utils.py:194} INFO - Collecting python-dateutil>=2.8.2 (from pandas==2.1.4->-r /tmp/venvp2zxfs_4/requirements.txt (line 1))
[2025-02-05T14:43:35.552+0000] {process_utils.py:194} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2025-02-05T14:43:35.606+0000] {process_utils.py:194} INFO - Collecting pytz>=2020.1 (from pandas==2.1.4->-r /tmp/venvp2zxfs_4/requirements.txt (line 1))
[2025-02-05T14:43:35.611+0000] {process_utils.py:194} INFO -   Using cached pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
[2025-02-05T14:43:35.655+0000] {process_utils.py:194} INFO - Collecting tzdata>=2022.1 (from pandas==2.1.4->-r /tmp/venvp2zxfs_4/requirements.txt (line 1))
[2025-02-05T14:43:35.699+0000] {process_utils.py:194} INFO -   Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2025-02-05T14:43:35.736+0000] {process_utils.py:194} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvp2zxfs_4/requirements.txt (line 1))
[2025-02-05T14:43:35.738+0000] {process_utils.py:194} INFO -   Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
[2025-02-05T14:43:35.742+0000] {process_utils.py:194} INFO - Using cached pandas-2.1.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.3 MB)
[2025-02-05T14:43:35.765+0000] {process_utils.py:194} INFO - Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.9 MB)
[2025-02-05T14:43:35.817+0000] {process_utils.py:194} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2025-02-05T14:43:35.820+0000] {process_utils.py:194} INFO - Using cached pytz-2025.1-py2.py3-none-any.whl (507 kB)
[2025-02-05T14:43:35.824+0000] {process_utils.py:194} INFO - Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)
[2025-02-05T14:43:35.828+0000] {process_utils.py:194} INFO - Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
[2025-02-05T14:43:35.888+0000] {process_utils.py:194} INFO - Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
[2025-02-05T14:43:54.336+0000] {job.py:229} INFO - Heartbeat recovered after 15.90 seconds
[2025-02-05T14:43:57.929+0000] {process_utils.py:194} INFO - Successfully installed numpy-1.26.4 pandas-2.1.4 python-dateutil-2.9.0.post0 pytz-2025.1 six-1.17.0 tzdata-2025.1
[2025-02-05T14:43:58.229+0000] {process_utils.py:194} INFO - 
[2025-02-05T14:43:58.233+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-05T14:43:58.234+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-05T14:43:58.564+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-02-05T14:43:58.595+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvp2zxfs_4/bin/python /tmp/venv-call1or4ygf4/script.py /tmp/venv-call1or4ygf4/script.in /tmp/venv-call1or4ygf4/script.out /tmp/venv-call1or4ygf4/string_args.txt /tmp/venv-call1or4ygf4/termination.log
[2025-02-05T14:43:58.600+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T14:44:00.096+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-05T14:44:00.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T14:44:00.132+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=external_signal_workflow, task_id=task_2, run_id=manual__2025-02-05T14:43:19.715570+00:00, execution_date=20250205T144319, start_date=20250205T144333, end_date=20250205T144400
[2025-02-05T14:44:00.218+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-05T14:44:00.219+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-05T14:44:00.238+0000] {logging_mixin.py:190} INFO - Dag name:external_signal_workflow queued_at:2025-02-05 14:43:19.745237+00:00
[2025-02-05T14:44:00.238+0000] {logging_mixin.py:190} INFO - Task hostname:***-worker-2 operator:PythonVirtualenvOperator
[2025-02-05T14:44:00.260+0000] {job.py:229} INFO - Heartbeat recovered after 13.87 seconds
[2025-02-05T14:44:00.283+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T14:44:00.346+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:44:00.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
