[2025-02-07T14:19:20.667+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T14:19:20.684+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T14:19:14.887679+00:00 [queued]>
[2025-02-07T14:19:20.693+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T14:19:14.887679+00:00 [queued]>
[2025-02-07T14:19:20.694+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T14:19:20.711+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): pre_deployment_checks> on 2025-02-07 14:19:14.887679+00:00
[2025-02-07T14:19:20.720+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T14:19:20.722+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-02-07T14:19:20.722+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'pre_deployment_checks', 'manual__2025-02-07T14:19:14.887679+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmpsqgwfmb7']
[2025-02-07T14:19:20.723+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask pre_deployment_checks
[2025-02-07T14:19:20.756+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T14:19:14.887679+00:00 [running]> on host 1999c8c59930
[2025-02-07T14:19:20.811+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='pre_deployment_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T14:19:14.887679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T14:19:14.887679+00:00'
[2025-02-07T14:19:20.812+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T14:19:20.812+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T14:19:20.813+0000] {logging_mixin.py:190} INFO - Current task name:pre_deployment_checks state:running start_date:2025-02-07 14:19:20.685378+00:00
[2025-02-07T14:19:20.813+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-07T14:19:20.814+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T14:19:20.815+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-07T14:19:20.816+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvx9eub5jo --system-site-packages --python=python
[2025-02-07T14:19:20.817+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:19:21.628+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 396ms
[2025-02-07T14:19:21.629+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvx9eub5jo, clear=False, no_vcs_ignore=False, global=True)
[2025-02-07T14:19:21.630+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-07T14:19:21.631+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-07T14:19:21.631+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-07T14:19:21.650+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvx9eub5jo/bin/pip install -r /tmp/venvx9eub5jo/requirements.txt
[2025-02-07T14:19:21.651+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:19:22.659+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvx9eub5jo/requirements.txt (line 1)) (2.1.4)
[2025-02-07T14:19:22.665+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvx9eub5jo/requirements.txt (line 1)) (1.26.4)
[2025-02-07T14:19:22.665+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvx9eub5jo/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-07T14:19:22.666+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvx9eub5jo/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:19:22.667+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvx9eub5jo/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:19:22.670+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvx9eub5jo/requirements.txt (line 1)) (1.17.0)
[2025-02-07T14:19:23.155+0000] {process_utils.py:194} INFO - 
[2025-02-07T14:19:23.156+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-07T14:19:23.156+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-07T14:19:23.233+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvx9eub5jo/bin/python /tmp/venv-call7ws5x3wy/script.py /tmp/venv-call7ws5x3wy/script.in /tmp/venv-call7ws5x3wy/script.out /tmp/venv-call7ws5x3wy/string_args.txt /tmp/venv-call7ws5x3wy/termination.log
[2025-02-07T14:19:23.234+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:19:25.417+0000] {process_utils.py:194} INFO - [2025-02-07T14:19:25.410+0000] {script.py:23} INFO - Starting pre-deployment checks...
[2025-02-07T14:19:25.497+0000] {process_utils.py:194} INFO - [2025-02-07T14:19:25.492+0000] {script.py:38} INFO - Pre-deployment checks completed
[2025-02-07T14:19:25.953+0000] {python.py:240} INFO - Done. Returned value was: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-07T14:19:25.473596'}
[2025-02-07T14:19:25.979+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T14:19:25.980+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=pre_deployment_checks, run_id=manual__2025-02-07T14:19:14.887679+00:00, execution_date=20250207T141914, start_date=20250207T141920, end_date=20250207T141925
[2025-02-07T14:19:25.993+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T14:19:25.993+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T14:19:25.993+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-07 14:19:14.922280+00:00
[2025-02-07T14:19:25.994+0000] {logging_mixin.py:190} INFO - Task hostname:1999c8c59930 operator:PythonVirtualenvOperator
[2025-02-07T14:19:26.027+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T14:19:26.052+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T14:19:26.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
