[2025-02-07T13:46:38.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T13:46:38.409+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.download_stack manual__2025-02-07T13:46:23.223832+00:00 [queued]>
[2025-02-07T13:46:38.420+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.download_stack manual__2025-02-07T13:46:23.223832+00:00 [queued]>
[2025-02-07T13:46:38.421+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T13:46:38.450+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): download_stack> on 2025-02-07 13:46:23.223832+00:00
[2025-02-07T13:46:38.523+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=93) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T13:46:38.525+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2025-02-07T13:46:38.526+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'download_stack', 'manual__2025-02-07T13:46:23.223832+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmpbaqess_3']
[2025-02-07T13:46:38.528+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask download_stack
[2025-02-07T13:46:38.602+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.download_stack manual__2025-02-07T13:46:23.223832+00:00 [running]> on host 35dedc08aa87
[2025-02-07T13:46:38.831+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='download_stack' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T13:46:23.223832+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T13:46:23.223832+00:00'
[2025-02-07T13:46:38.834+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T13:46:38.834+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T13:46:38.835+0000] {logging_mixin.py:190} INFO - Current task name:download_stack state:running start_date:2025-02-07 13:46:38.409749+00:00
[2025-02-07T13:46:38.835+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-07T13:46:38.835+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T13:46:38.836+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-07T13:46:38.838+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv9mguf7zz --system-site-packages --python=python
[2025-02-07T13:46:38.846+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T13:46:39.988+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 527ms
[2025-02-07T13:46:39.994+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv9mguf7zz, clear=False, no_vcs_ignore=False, global=True)
[2025-02-07T13:46:39.995+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-07T13:46:39.996+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-07T13:46:39.997+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-07T13:46:40.012+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv9mguf7zz/bin/pip install -r /tmp/venv9mguf7zz/requirements.txt
[2025-02-07T13:46:40.014+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T13:46:41.180+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv9mguf7zz/requirements.txt (line 1)) (2.1.4)
[2025-02-07T13:46:41.188+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv9mguf7zz/requirements.txt (line 1)) (1.26.4)
[2025-02-07T13:46:41.189+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv9mguf7zz/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-07T13:46:41.191+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv9mguf7zz/requirements.txt (line 1)) (2024.2)
[2025-02-07T13:46:41.192+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv9mguf7zz/requirements.txt (line 1)) (2024.2)
[2025-02-07T13:46:41.195+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venv9mguf7zz/requirements.txt (line 1)) (1.17.0)
[2025-02-07T13:46:41.731+0000] {process_utils.py:194} INFO - 
[2025-02-07T13:46:41.732+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-07T13:46:41.733+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-07T13:46:41.867+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv9mguf7zz/bin/python /tmp/venv-callq9fw3p4s/script.py /tmp/venv-callq9fw3p4s/script.in /tmp/venv-callq9fw3p4s/script.out /tmp/venv-callq9fw3p4s/string_args.txt /tmp/venv-callq9fw3p4s/termination.log
[2025-02-07T13:46:41.869+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T13:46:43.817+0000] {process_utils.py:194} INFO - [2025-02-07T13:46:43.816+0000] {script.py:24} INFO - Starting download stack...
[2025-02-07T13:46:53.848+0000] {process_utils.py:194} INFO - [2025-02-07T13:46:53.846+0000] {script.py:40} INFO - Download stack completed:
[2025-02-07T13:46:53.852+0000] {process_utils.py:194} INFO - Total size: 1200.0MB
[2025-02-07T13:46:53.853+0000] {process_utils.py:194} INFO - Total time: 240s
[2025-02-07T13:46:53.853+0000] {process_utils.py:194} INFO - Download speed: 5.0MB/s
[2025-02-07T13:46:54.333+0000] {python.py:240} INFO - Done. Returned value was: {'stacks': ['baseos', 'gi'], 'total_size_mb': 1200.0, 'total_time_seconds': 240, 'download_speed_mbs': 5.0, 'status': 'success', 'details': [{'stack': 'baseos', 'size_mb': 1000, 'status': 'completed', 'time': 180}, {'stack': 'gi', 'size_mb': 200, 'status': 'completed', 'time': 60}], 'timestamp': '2025-02-07T13:46:53.845757'}
[2025-02-07T13:46:54.360+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T13:46:54.361+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=download_stack, run_id=manual__2025-02-07T13:46:23.223832+00:00, execution_date=20250207T134623, start_date=20250207T134638, end_date=20250207T134654
[2025-02-07T13:46:54.371+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T13:46:54.371+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T13:46:54.372+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-07 13:46:23.239307+00:00
[2025-02-07T13:46:54.372+0000] {logging_mixin.py:190} INFO - Task hostname:35dedc08aa87 operator:PythonVirtualenvOperator
[2025-02-07T13:46:54.418+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T13:46:54.440+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T13:46:54.441+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
