[2025-02-05T13:13:43.115+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T13:13:43.125+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: external_signal_workflow.task_1 manual__2025-02-05T13:08:36.538537+00:00 [queued]>
[2025-02-05T13:13:43.132+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: external_signal_workflow.task_1 manual__2025-02-05T13:08:36.538537+00:00 [queued]>
[2025-02-05T13:13:43.132+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-05T13:13:43.260+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): task_1> on 2025-02-05 13:08:36.538537+00:00
[2025-02-05T13:13:43.306+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=902) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T13:13:43.312+0000] {standard_task_runner.py:72} INFO - Started process 903 to run task
[2025-02-05T13:13:43.314+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'external_signal_workflow', 'task_1', 'manual__2025-02-05T13:08:36.538537+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/external_signal_workflow.py', '--cfg-path', '/tmp/tmpq8zp4toi']
[2025-02-05T13:13:43.317+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask task_1
[2025-02-05T13:13:43.448+0000] {task_command.py:467} INFO - Running <TaskInstance: external_signal_workflow.task_1 manual__2025-02-05T13:08:36.538537+00:00 [running]> on host ***-worker-2
[2025-02-05T13:13:43.522+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='external_signal_workflow' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T13:08:36.538537+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T13:08:36.538537+00:00'
[2025-02-05T13:13:43.523+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-05T13:13:43.523+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-05T13:13:43.524+0000] {logging_mixin.py:190} INFO - Current task name:task_1 state:running start_date:2025-02-05 13:13:43.126664+00:00
[2025-02-05T13:13:43.524+0000] {logging_mixin.py:190} INFO - Dag name:external_signal_workflow and current dag run status:running
[2025-02-05T13:13:43.524+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T13:13:43.524+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-05T13:13:43.525+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvk1t1eunx --system-site-packages --python=python
[2025-02-05T13:13:43.531+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T13:13:44.312+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 302ms
[2025-02-05T13:13:44.313+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvk1t1eunx, clear=False, no_vcs_ignore=False, global=True)
[2025-02-05T13:13:44.314+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-05T13:13:44.315+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-05T13:13:44.315+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-05T13:13:44.334+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvk1t1eunx/bin/pip install -r /tmp/venvk1t1eunx/requirements.txt
[2025-02-05T13:13:44.336+0000] {process_utils.py:190} INFO - Output:
[2025-02-05T13:13:45.404+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvk1t1eunx/requirements.txt (line 1)) (2.1.4)
[2025-02-05T13:13:45.410+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvk1t1eunx/requirements.txt (line 1)) (1.26.4)
[2025-02-05T13:13:45.410+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvk1t1eunx/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-05T13:13:45.411+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvk1t1eunx/requirements.txt (line 1)) (2024.2)
[2025-02-05T13:13:45.411+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvk1t1eunx/requirements.txt (line 1)) (2024.2)
[2025-02-05T13:13:45.413+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvk1t1eunx/requirements.txt (line 1)) (1.17.0)
[2025-02-05T13:13:45.875+0000] {process_utils.py:194} INFO - 
[2025-02-05T13:13:45.875+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-05T13:13:45.876+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-05T13:13:45.934+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.935+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.935+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.935+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.936+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.936+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.936+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.937+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.937+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.938+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.938+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.938+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/operators/python.py:535: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  op_kwargs: dict[str, Any] = dict(self.op_kwargs)

[2025-02-05T13:13:45.938+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-02-05T13:13:45.939+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.940+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.940+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.940+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.941+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.941+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.941+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.942+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.942+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.942+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.942+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.943+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:380: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  items = [(key, self[key]) for key in self._context]

[2025-02-05T13:13:45.964+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 544, in _execute_python_callable_in_subprocess
    self._write_args(input_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _write_args
    file.write_bytes(self.pickling_library.dumps({"args": self.op_args, "kwargs": self.op_kwargs}))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'module' object
[2025-02-05T13:13:45.977+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-05T13:13:45.978+0000] {logging_mixin.py:190} INFO - Task start:2025-02-05 13:13:43.126664+00:00 end:2025-02-05 13:13:45.976674+00:00 duration:2.85001
[2025-02-05T13:13:45.979+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonVirtualenvOperator): task_1> dag:<DAG: external_signal_workflow> dagrun:<DagRun external_signal_workflow @ 2025-02-05 13:08:36.538537+00:00: manual__2025-02-05T13:08:36.538537+00:00, state:running, queued_at: 2025-02-05 13:08:36.572615+00:00. externally triggered: True>
[2025-02-05T13:13:45.979+0000] {logging_mixin.py:190} INFO - Failure caused by cannot pickle 'module' object
[2025-02-05T13:13:45.979+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=external_signal_workflow, task_id=task_1, run_id=manual__2025-02-05T13:08:36.538537+00:00, execution_date=20250205T130836, start_date=20250205T131343, end_date=20250205T131345
[2025-02-05T13:13:45.994+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T13:13:45.995+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task task_1 (cannot pickle 'module' object; 903)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 544, in _execute_python_callable_in_subprocess
    self._write_args(input_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _write_args
    file.write_bytes(self.pickling_library.dumps({"args": self.op_args, "kwargs": self.op_kwargs}))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot pickle 'module' object
[2025-02-05T13:13:46.043+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-05T13:13:46.075+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T13:13:46.079+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
